name: Run Pytest
permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        include:
          - python-version: "3.10"
            cache: true

    steps:
      # - name: Maximize build space (#1)
      #   uses: mathio/gha-cleanup@aca3d43a05bf564f5fc69acb929a65b01797f22b
      #   with:
      #     remove-browsers: true
      #     verbose: true

      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install --system -e .[dev]

      - name: Restore test data from cache
        id: cache
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: tests/data
          key: zenodo-17529862-small

      - name: Download test data from Zenodo (cache miss)
        if: steps.cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p tests/data
          cd tests/data

          # Download both files with retries and resume
          # curl -L --fail --retry 5 --retry-delay 5 --continue-at - \
          #   -o zarr_particle_tools_test_data_large.tar.gz \
          #   "https://zenodo.org/records/17529862/files/zarr_particle_tools_test_data_large.tar.gz?download=1"

          curl -L --fail --retry 5 --retry-delay 5 --continue-at - \
            -o zarr_particle_tools_test_data_small.tar.gz \
            "https://zenodo.org/records/17529862/files/zarr_particle_tools_test_data_small.tar.gz?download=1"

      - name: Save test data to cache
        if:  ${{ matrix.cache && steps.cache.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: tests/data
          key: zenodo-17529862-small

      - name: Extract test data from tar.gz files
        run: |
          # Extract
          cd tests/data
          for f in *.tar.gz; do tar -xzf "$f"; done

      - name: List contents
        run: ls -lah tests/data

      - name: Run tests
        run: |
          pytest -n 1 -vvv -k "not (local and unroofing)"
        timeout-minutes: 60
